### ISSUE TITLE
Alertmanager cannot use `local` storage anymore

### ISSUE THREAD

**Issue by pstibrany** [grafana/mimir#1638]
#### Describe the bug

Attempt to configure Alertmanager with `local` storage ends with `the configured alertmanager storage backend is not supported when sharding is enabled` error. But alertmanager sharding is not optional anymore in Grafana Mimir.

#### Expected behavior

Either make `local` work, or drop support for it.

Originally reported #mimir channel: https://grafana.slack.com/archives/C039863E8P7/p1649168943502349?thread_ts=1649141342.323589&cid=C039863E8P7.

**Comment by RixTmobilender** [comment]
I just hit this as well.

My interest is in automating the configuration of recording and alerting rules without any post-deployment actions (be it mimirtool or HTTP API) in Kubernetes. Preferably through mounted configmaps similar to [Cortex's guide ](https://github.com/cortexproject/cortex-helm-chart/wiki/Dynamically-configure-Rules-and-Alertmanager-via-sidecar)

The ruler already supports[ sharding in local mode](https://grafana.com/docs/mimir/v2.0.x/operators-guide/architecture/components/ruler/) when the recording rules are exactly the same:
> When all rulers have the same rule files, local storage supports ruler sharding. To facilitate sharding in Kubernetes, mount a [Kubernetes ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) into every ruler pod.

Would it be possible to do the same for the alertmanager?

**Comment by pracucci** [comment]
> Either make local work, or drop support for it.

@gotjosh have you thoughts about this?

**Comment by stevesg** [comment]
I have some background here:

Alertmanager ("sharding") takes snapshots of its internal state so that it can recover from an all-replica outage. This should be to remote storage (e.g. GCS, S3,...), so that the state for a tenant is not tied to a specific replica. We decided to have this state stored in the same place that you store the alertmanager configurations (e.g. the bucket that contains your configurations uploaded via the API, also contains the state snapshots).

Therefore, the `local` backend is not suitable for use with sharding, because it is conceptually read-only. Therefore, the Persister component cannot write state out.

The easiest option to fix this would be to allow alertmanager to start with `local` if the `Persister` is disabled. This would be fine for configurations where sharding is not needed (e.g. number of replicas == replication factor), because state is still written to local disk too (we considered disabling this, but have yet to do the work).
