### ISSUE TITLE
Change -querier.shuffle-sharding-ingesters-lookback-period default to leverage on ingesters shuffle-sharding by default

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#1810]
Querier leverages on ingesters shuffle sharding only if `-querier.shuffle-sharding-ingesters-lookback-period` is set to a value greater than 0. The default value is 0, so by default a querier always query **all** ingesters for **every** tenant.

I propose to change `-querier.shuffle-sharding-ingesters-lookback-period` default so that it's auto-detected and internally set to the max between `-querier.query-store-after` and `-querier.query-ingesters-within`. The reason why I wouldn't remove it is because we still a way to disable ingesters shuffle-sharding on read path only (used during some migrations, reason why it's supported by our jsonnet). Alternatively, we could drop this option and introduce a new boolean option to disable ingesters shuffle sharding on read path only.

_Thoughts?_

**Comment by pracucci** [comment]
> The default value is 0, so by default a querier always query all ingesters for every tenant.

#1921 changed default to 13h. However, the point of this issue is still valid: should we just auto tune it?

**Comment by replay** [comment]
I can see no disadvantage in auto-tuning it. 
Furthermore, by auto-tuning it we might be able to prevent that users shoot themselves in the foot by increasing one of `-querier.query-store-after` or `-querier.query-ingesters-within` without also updating `-querier.shuffle-sharding-ingesters-lookback-period` accordingly, this is an advantage.

> Alternatively, we could drop this option and introduce a new boolean option to disable ingesters shuffle sharding on read path only.

Are there any migration scenarios in which it can be useful to define the lookback period explicitly, instead of only enabling it and then relying on the auto-tuning to determine the correct value? I cannot think of a scenario where this would be necessary, so replacing it with a bool seems like a good idea.

Another thought:
Are there any valid configurations where `-querier.query-store-after` would be larger than `-querier.query-ingesters-within`? 
If not, then determining the best value for `-querier.shuffle-sharding-ingesters-lookback-period` would be simple, we could just take the value of `-querier.query-ingesters-within` and we wouldn't need to look at `-querier.query-store-after` at all.

**Comment by 56quarters** [comment]
My plan for this issue is:
* Deprecate `-querier.shuffle-sharding-ingesters-lookback-period`
* Add `-querier.shuffle-sharding-ingesters-enabled`, defaulting to true
* Use the value of `-querier.query-ingesters-within` internally where `-querier.shuffle-sharding-ingesters-lookback-period` was previously used
* Update documentation to use `-querier.query-ingesters-within` and `-querier.shuffle-sharding-ingesters-enabled` where appropriate.

**Comment by 56quarters** [comment]
I'm struggling to understand what the correct behavior should be in the following case:
* `-querier.query-ingesters-within=0`
* `-querier.shuffle-sharding-ingesters-enabled=true`

In this case we:
* Always query ingesters, regardless of the time range
* Use a [lookback of `0`](https://github.com/grafana/mimir/blob/ee7c0639a105c8b39cb0ad88f4f7ee600fe1673c/vendor/github.com/grafana/dskit/ring/ring.go#L628) when determining which ingesters should be part of the shuffle sharding subring which means whatever ingester currently owns a token is included (because `ingester.RegisteredTimestamp` is always < `lookbackUntil`, since `lookbackUntil` is `$NOW` [in this case](https://github.com/grafana/mimir/blob/ee7c0639a105c8b39cb0ad88f4f7ee600fe1673c/vendor/github.com/grafana/dskit/ring/ring.go#L693-L697)).

This behavior is equivalent to using the following options (with current versions of Mimir):
* `-querier.query-ingesters-within=0`
* `-querier.shuffle-sharding-ingesters-lookback-period=1ns`

My question is:
* Does the new behavior sound correct?
* Is the new behavior possible to understand?
* Is the new behavior what users will expect when combining these options?

**Comment by Logiraptor** [comment]
> Only query shuffle sharding subring of ingesters when both -querier.shuffle-sharding-ingesters-enabled=true is set and -querier.query-ingesters-within is > 0.

If I'm understanding correctly, `-querier.query-ingesters-within=0` behaves more like `-querier-query-ingesters-within=infinity` (made up value). So any ingester that could have *ever* been responsible for a series should be queried, which is the same as just disabling shuffle sharing on the read path. This approach makes the most sense to me.

**Comment by osg-grafana** [comment]
It sounds like this issue requires a change to documentation.

**Comment by pracucci** [comment]
> > Only query shuffle sharding subring of ingesters when both -querier.shuffle-sharding-ingesters-enabled=true is set and -querier.query-ingesters-within is > 0.
> 
> If I'm understanding correctly, `-querier.query-ingesters-within=0` behaves more like `-querier-query-ingesters-within=infinity` (made up value). So any ingester that could have _ever_ been responsible for a series should be queried, which is the same as just disabling shuffle sharing on the read path. This approach makes the most sense to me.

☝️ I think this is a good compromise.
