### ISSUE TITLE
Add a warning alert if a Mimir component doesn't own any tenant

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#1959]
In #1882 we added the alert `MimirStoreGatewayNoSyncedTenants` which fires if a store-gateway doesn't own any tenant (could reveal a misconfiguration).

We could introduce a similar alert for other components supporting shuffle-sharding:
- Ingesters: `cortex_ingester_memory_users == 0`
- Rulers: `cortex_ruler_managers_total == 0`
- Alertmanager: `cortex_alertmanager_tenants_owned == 0`

> Ruler and Alertmanager

Contrary to store-gateways or ingesters, it's legit to have ruler and alertmanager deployed (e.g. because installed via Helm or Jsonnet) with no evaluating rules. In this case we don't want the alert to fire. To solve this false positive, we could write the alert query to fire if an instance owns no tenants, but other instances do.

**Comment by replay** [comment]
> Contrary to store-gateways or ingesters, it's legit to have ruler and alertmanager deployed (e.g. because installed via Helm or Jsonnet) with no evaluating rules. To solve this false positive, we could write the alert query to fire if an instance owns no tenants, but other instances do.

To prevent that these alerts start to fire right after deploying a new cluster and before it ingests any data, would it make sense to also make the ingester/store-gw alerts only fire if there are other instances which do own some tenants? 
Otherwise, if a new cluster gets deployed and directly fires alerts because it has no data yet, couldn't that confuse a user and make them wrongly think that something is misconfigured?

**Comment by pstibrany** [comment]
Reopening, as #3681 only added alert for ingester.

**Comment by pracucci** [comment]
We still have very limited experience with RW deployment mode. I would move forward with these alerts and further improve them once we'll see them running in real clusters running with RW mode.
