### ISSUE TITLE
Idea: move tenant federation to query-frontend middleware

### ISSUE THREAD

**Issue by 56quarters** [grafana/mimir#2715]
#### Is your feature request related to a problem? Please describe.

Currently, tenant federation (using a single request to query multiple tenants) is implemented as a `Queryable`/`Querier` in the querier component itself. A consequence of this is that extremely parallel work (same query, different tenants) is limited to a single querier, capped at a max parallelism of 16.

#### Describe the solution you'd like

In the same way that the query-frontend splits queries by time range, sharding, etc. - it could split them by tenant. This would allow faster execution when there are more than 16 tenants being queried at once (this can easily happen in GEM when using the `*` wildcard tenant) and more predictable resource usage: the query frontend would be responsible for splitting the query, not an individual querier.

#### Describe alternatives you've considered

Doing nothing, let tenant federation queries continue to be parallelized by the queriers.

**Comment by bboreham** [comment]
I was trying to remember why it wasn’t done this way in the first place, and I realised this is much more like query-sharding than slicing by day. 
Federated queries can do things like max over all tenants, which requires that we run the PromQL engine again once we have all the pieces.
Point is: we didn’t have the machinery to do this until a few months ago.

**Comment by mattmendick** [comment]
@56quarters is this a `good first issue` type issue or is it more involved?

**Comment by colega** [comment]
@mattmendick I don't think this is as easy as a good first issue. I agree with @bboreham about this being more a query-sharding-like than split by day. The issue I see is that not all queries can be sharded, some of them can't be, so we'll still have to keep the tenant federation in the querier.

An idea we discussed in the weekly meeting is to actually use query-sharding to issue tenant-specific queries and recompose the result, when possible. So instead of querying `__query_shard__="x_of_y"` it would query `__tenant_id__="z"`, with a previous middleware hinting the list of tenant ids to query.

**Comment by 56quarters** [comment]
Based on some discussion, I've opened #5874 which allows the tenant federation concurrency to be adjusted (instead of hardcoded at 16). This is instead of potentially making large changes to the way tenant federation works as described in this issue.
