### ISSUE TITLE
Helm: Update all values with proper helm-docs docstring

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#2854]
- [ ] Add section in README.gotmpl to generate the values documentation
- [ ] Improve helm-docs if needed to break up the values table into parts (add pagebreak/section break?)
- [ ] Have doc string for all values (take inspiration from loki)
- [ ] Improve helm-docs to be able to have examples in the docstings using preformatted text/code snippets
- [ ] Reorder values to be consistent across all services
- [ ] Clarify which section is enterprise only and which is OSS only (customer feedback)

**Comment by dimitarvdimitrov** [comment]
the reason this was reopened is that we plan to use these doc strings to document the helm chart. The idea is that users use the README and the values.yaml to get started with a chart instead of searching for external documentation. We can also generate documentation based on these docstrings, which we can put on grafana.com

**Comment by osg-grafana** [comment]
Closing due to age and low priority. Reopen if priority increases.
