### ISSUE TITLE
Docs: Provided dashboard mixins aren't accurate

### ISSUE THREAD

**Issue by altokarev** [grafana/mimir#2973]
Hey there! 👋 

I pushed [these dashboards](https://github.com/grafana/mimir/tree/main/operations/mimir-mixin-compiled/dashboards) to my Grafana and noticed that some dashboards shows "No data" placeholders.

<img width="1212" alt="CleanShot 2022-09-17 at 22 10 47@2x" src="https://user-images.githubusercontent.com/28726429/190873457-6a632f9c-1cce-4b99-a405-b0c18a25df8c.png">

Seems some expressions are not accurate and contains some Cortex-only related formations, e.g.:

https://github.com/grafana/mimir/blob/d7266d0c1cfa02e4e55bcfde642bfba1ac795470/operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json#L551

AFAIK there are no [components](https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/) named `gateway`, `cortex-gw` or `cortex-gw-internal` in a Mimir package.

Sadly, I'm not able to contribute here due to lack of a Mimir's knowledge, but I think it's better to re-validate the code of all dashboard mixins.

**Comment by altokarev** [comment]
Oh, seems this dashboard could only be used with Enterprise Metrics. That's kinda confusing at first sight, but now I see 🙂

**Comment by pracucci** [comment]
A couple of notes:
1. Some panels requires recording rules. Make sure to install the provided recording rules too. For more information, [see doc](https://grafana.com/docs/mimir/latest/operators-guide/monitor-grafana-mimir/installing-dashboards-and-alerts/).
2. The gateway panels are disabled by default (because gateway is not part of Mimir) but you're right that it's still used in the "Rollout progress" dashboard (the one you shared the screenshot), because that's how we currently gather QPS metrics. We should improve it.

**Comment by altokarev** [comment]
Yes, I've installed additional recording rules, for sure.

Thanks for the response, Marco 🙏
