### ISSUE TITLE
Fix link [For details about the sizing plans, see Capacity planning and Pod scheduling.]

### ISSUE THREAD

**Issue by davidr-bt** [grafana/mimir#3491]
The link in https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/README.md for "For details about the sizing plans, see Capacity planning and Pod scheduling" is broken.

**Comment by pracucci** [comment]
Thanks for reporting! @Logiraptor what should be the right link destination?

**Comment by Logiraptor** [comment]
Looks like that link is merged to the Readme in anticipation of the next release. The content can be found at:

https://grafana.com/docs/mimir/next/operators-guide/run-production-environment-with-helm/#plan-capacity

(Notice the `/next` instead of `/latest`). The README link will work once we publish the upcoming Mimir 2.5 release.

Taking a step back, we'll eventually have separate docs for Helm so they aren't tied to Mimir releases in this way. That's being tracked in #2395

**Comment by osg-grafana** [comment]
Looks like this has been fixed, therefore closing.
