### ISSUE TITLE
[limits] ingester.instance-limits.max-series returns 500 errors and not 429

### ISSUE THREAD

**Issue by gouthamve** [grafana/mimir#3589]
#### Describe the bug

Hitting `-ingester.instance-limits.max-series` returns a 500 error and not a 429.

#### To Reproduce

Set the limit to be `5` and then send more than 5 series.

#### Expected behavior

It should return a 429 so the data is not retried and remote_write is not blocked.

#### Additional Context

This is because we set the limit on `PreCreate` hook which is called on `Append()` and `Append()` fails. And this is treated like a generic `Append()` error, and not a rate-limit.

**Comment by 56quarters** [comment]
We return a 500 here on purpose. This is a per-ingester limit, unrelated to what a user is trying to do. Hitting any of the per-ingester limits will return 5XX errors. It's not a 429 because there's nothing the user can do to fix this on their side: _they_ aren't sending too many metrics, we've configured our ingesters wrong.

**Comment by gouthamve** [comment]
Interesting, I see. Happy to close this then.

**Comment by pracucci** [comment]
> We return a 500 here on purpose. This is a per-ingester limit, unrelated to what a user is trying to do. Hitting any of the per-ingester limits will return 5XX errors. It's not a 429 because there's nothing the user can do to fix this on their side: _they_ aren't sending too many metrics, we've configured our ingesters wrong.

There's also another reason: we want Prometheus to retry in this case.
