### ISSUE TITLE
rollout-operator missing %d

### ISSUE THREAD

**Issue by ishworg** [grafana/mimir#3969]
#### Describe the bug
Fresh mimir installation, log lines of rollout-operator spews:
```
mimir-release-rollout-operator-fd5c6d5f8-9zvhx rollout-operator level=warn ts=2023-01-17T00:24:32.918590218Z msg="%d StatefulSets have some not-Ready pods, skipping reconcile" 3=(MISSING)

```

#### To Reproduce

1. Install fresh Mimir using helm 
2. Check rollout-operator's log

installation: 
```
helm --namespace mimir install mimir-release grafana/mimir-distributed \
  --debug
```

```
helm -n mimir  list
NAME            NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                   APP VERSION
mimir-release   mimir           1               2023-01-17 11:22:57.765351625 +1100 AEDT        deployed        mimir-distributed-4.0.1 2.5.0     
```

#### Expected behavior

log lines needs a value for the  missing `%d`.
```
msg="%d StatefulSets have some not-Ready pods, skipping reconcile" 3=(MISSING)
```

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

**Comment by charleskorn** [comment]
Hi @ishworg 👋 This was fixed in https://github.com/grafana/rollout-operator/pull/19, which was released as part of v0.1.2 of the rollout-operator.

Could you double-check what version of the rollout-operator is running?

**Comment by ishworg** [comment]
@charleskorn thanks

The image in helm is set to use: `v0.1.1`. I used default values file.

Introspecting the container on k8s confirms it is so:
```
    Image:         grafana/rollout-operator:v0.1.1
```

**Comment by charleskorn** [comment]
The current release (v4.0.1) of the `mimir-distributed` chart refers to v0.1.1 of the rollout operator chart - the next release of the `mimir-distributed` chart will use a later version, which contains the fix for this issue.

If this log message is causing issues and you don't want to wait for the release, you could try the latest pre-release version of the `mimir-distributed` chart, `4.1.0-weekly.220`. Note that this deploys a pre-release version of Mimir as well.

**Comment by ishworg** [comment]
perfect. thanks @charleskorn
