### ISSUE TITLE
Investigate and fix unbalanced series between ingesters (no shuffle sharding)

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#4736]
While running Mimir in production (and Cortex before) we've always observed some unbalanced series between ingesters. This unbalance exists both when shuffle sharding is enabled and disabled, even if it's even more emphasised when shuffle sharding is enabled.

For example, the following Mimir cluster shows a 25% spread between the ingester with the lowest and higher number of series:

![Screenshot 2023-04-14 at 15 24 57](https://user-images.githubusercontent.com/1701904/232056136-de61a4e4-9e71-497a-843e-0a2395c96200.png)

This issue tracks the investigation and discussion of how to fix it in the case shuffle sharding is not used. When shuffle sharding is used, it adds extra complexity to fix it, but I believe we first have to fix it for the "no shuffle sharding" case and then move to shuffle sharding (because shuffle sharding was designed on the expectation that series for a given tenant are evenly sharded between ingesters of its shard).

**Comment by pracucci** [comment]
## How much the "number of tokens per ingester" impact the spread between ingesters?

I've run a simulation to check how the "tokens ownership spread" (which is the difference in % between the tokens owned by the lowest and highest ingester) change based on changing the number of tokens per ingester:

![Screenshot 2023-04-14 at 15 33 24](https://user-images.githubusercontent.com/1701904/232057957-e5c3c626-1e01-4f21-b573-5a8591a95c3b.png)

How the spread changes (lower is better):
- 64 tokens per ingester: 52%
- 128 tokens per ingester: 41%
- 256 tokens per ingester: 32%
- 512 tokens per ingester: 24%
- 1024 tokens per ingester: 17%
- 2048 tokens per ingester: 12%
- 4096 tokens per ingester: 9%
- 8192 tokens per ingester: 6%

**Comment by pracucci** [comment]
## Is `crypto/rand` better than `math/rand`?

No.

`ring.GenerateTokens()` uses `math/rand`, so I've run the simulation changing it with `crypto/rand` and the spread I got is the same.

**Comment by duricanikolic** [comment]
This weekend I played a bit with the tool created by @pracucci and extended it a bit in the following way:
- the first ingesters per zone will be assigned a tooken randomly, but they will be "almost" equidistant one from another ([here](https://github.com/grafana/mimir/blob/yuri/analyse-unbalanced-series/tools/analyse-unbalanced-series/ring_simulation_per_zone.go#L96))
- tokens of all other ingesters are distributed by using this strategy: in each moment the biggest ring range **from the same zone** is split in 2 parts, and a new token is added in the middle (if not already taken by another ingester from another zone, otherwise the first available one is found). Token infos containing tokens info and sizes are connected via a doubly-linked list and a priority queue is used for choosing the next one ([here](https://github.com/grafana/mimir/blob/yuri/analyse-unbalanced-series/tools/analyse-unbalanced-series/ring_simulation_per_zone.go#L18)).

Then I did some analyses to see :
- **A1**: how the distribution of tokens will be done for ingesters during their registration by fixing the number of ingesters and choosing different number of tokens (see the [results](https://docs.google.com/spreadsheets/d/13Dhyr1xRT57LJWgVzsc8XoG0y9dQv7g26GkGC6TxPu8/edit#gid=0)), and 
- **A2**: also if we fix the number of ingesters and number of tokens, create the distribution by using the approach above, and then generating tokens randomly (to simulate timeseries to be handled) and see to which ingesters they would be assigned. 

I didn't get perfect results, but I am glad I did this exercise. In analysis **A1** I calculated both "spreads" per-zone and for all ingesters. The later is pretty bad, but the former is actually good: depending from the combination of number of ingester - number of tokens per ingester we actually get either spread 0 or spred 0.5. The question is: which spreads should we be more concerned about: per-zone or in total? I guess the answer is both. This is also what Cassandra tries to achieve, and I would like to try to apply their-like algorithm (which is pretty complecated but I studied it a lot in the last days) and see how it works. The good thing with this approach is that we don't need a huge number of tokens per ingester.
In analysis A2 I simulated different scenarios (by changing the number of ingesters, tokens, zone-awareness, replication factor and number of series). Again the results are not perfect at all, because there are big differences in spreads, but if I am not mistaken there are usually only 2-3 groups of spreads where the majority of ingesters belong to. [The "best" analysis that I got was when I chose 512 ingesters (I was tired and I didn't realize that 512%3!=0), 64 tokens per ingester, zone-awareness enabled, RF=3 and 10M series:](https://docs.google.com/spreadsheets/d/13Dhyr1xRT57LJWgVzsc8XoG0y9dQv7g26GkGC6TxPu8/edit#gid=736353658) **The spread was only 4.5%**. I don't know whether it was just a lucky case, but the result is this one and the analysis took ages to complete.

Some thoughts: 
- maybe we should try to chose candidate tokens in Cassandra-way (by selecting the best one which minimizes the spread in its zone and in general at each step)
- should we try Murmur3Partitioner for chosing the tokens randomly?

**Comment by krajorama** [comment]
Increasing the number of tokens can mitigate the effect, especially if the current number of tokens is relatively small (64). 
Feedback on Grafana Mimir community call: the migration is non-trivial in large clusters due to https://github.com/grafana/dskit/pull/79 . Need to prioritize.

**Comment by duricanikolic** [comment]
### Changes of ring topology ###
I have done an additional test: I started from a generated ring of 66 instances with a certain number of tokens per instance, and I collected all standard deviations from the current optimal ownership while I was:
1. first adding 66 instances one-by-one, 
2. and then removing the added 66 instances one-by-one in the LIFO mode.
This was done for rings generated with different number of tokens per instance, and for both approaches. _This somehow simulates the regular scaling up and scaling down of instances._ The results are shown in the following chart. 

**Note:** Next week I want to simulate removals of random instances (from a random zone) and consecutive addition of another instance in the same zone. This should simulate an unexpected instance restart.

- The x-axis represents the number of instances in the ring: 66, 68a (meaning 68 instances after an instance is added), ..., 132a (meaning 132 after an instance is added), 130r (meaning 130 after an instance is removed), ..., 66r (meaning 66 after an instance is removed).
- The y-axis represents the standard deviation from the optimal token ownership (when having the number of instances on the x-axis)
- We can see that, as expected, in all analysed cases, **the standard deviation after removal of an instance is equal to the standard deviation before its addition, if we add and remove instances in the same order**. 

![StDevByAddingAndRemoving](https://github.com/grafana/mimir/assets/1186801/7bdaaab9-a178-427e-894f-2828193ee0d7)

**Comment by duricanikolic** [comment]
### Spread comparison ###
If, instead of using standard deviation from optimal token distribution, we wanted to compare the spread, i.e., the difference between ingester with the highest and the lowest token ownership ($\frac{max - min}{max}$), we obtain the following results.

**Note:** we can notice that with _higher number of tokens per instance_ (128+) the _random token selection approach gives lower spread_. It is, though, worth noting that the **candidate selection approach selects candidates in such a way that the difference between the standard deviation from the optimal token ownership before and after adding a new token is minimal**. Therefore this comparison is not perfect. Maybe it makes sense to define and analyze another approach in which candidates are selected related to the spread.

- comparison of spread in rings of 66 instances with variable tokens each built by using the candidate selection approach and by random token selection
![SpreadComparisonRF3ZAE](https://github.com/grafana/mimir/assets/1186801/a654ea73-0d03-4044-bc1a-f055fe6b558b)
- comparison of spread of distributions of 10M timeseries in rings of 66 instances with variable tokens each built by using the candidate selection approach and by random token selection
![SpreadComparsion10MSeries66InstRF3ZAE](https://github.com/grafana/mimir/assets/1186801/913ed0ff-93b8-49e0-b16e-8bec154f8744)
- comparison of spread of distributions of 10M timeseries in rings of 513 instances with variable tokens each built by using the candidate selection approach and by random token selection
![SpreadComparison10MSeries513InstRF3ZAE](https://github.com/grafana/mimir/assets/1186801/5e96d075-5000-40a3-b7cd-eed4e6d6b418)

**Comment by duricanikolic** [comment]
I was thinking about generating the tokens for the first instance per zone like this, and then to add tokens for all consecutive instances in the middle between 2 existing tokens in the same zone: 
```go
func tokens(tokenCount, zoneCount int) [][]uint32 {
  tokensPerZone := make([][]uint32, 0, zonesCount)
  for z := 0; z < zonesCount; z++ {
    tokensPerZone = append(tokensPerZone, make([]uint32, 0, tokensPerInstanceCount))
      for t := 0; t < tokensPerInstanceCount; t++ {
        token := uint32(math.Pow(2, 32)*(1.0-(3.0*float64(t)+float64(zonesCount)))/float64(zonesCount*tokensPerInstanceCount)) - 1
        tokensPerZone[z] = append(tokensPerZone[z], token)
      }
      slices.Sort(tokensPerZone[z])
  }
  return tokensPerZone
}
```

**Comment by duricanikolic** [comment]
The Cassandra-like approach has been abandoned, and we have opted for a different one, called _spread minimizing approach_. Assuming that each instance owns `tokensPerInstance` tokens and that there are `zoneCount` zones, given an instance id `instanceID` and zone id `zoneID` to which this instance belongs to, we build the tokens for that instance assuming that the tokens of all other instances having ids lower than the given one are present, as follows:
- if `instanceID == 0`, we evenly distribute the `tokensPerInstance` tokens in the ring, such that for each token `token`, ```token%zonesCount == zoneID```.
- if `instanceID != 0`, we first calculate the optimal token ownership `optimalInstanceOwnership` for the instances in the ring as $\frac{2^{32}}{instanceID + 1}$, and then we try to assign that ownership to the new instance. It is done in `tokensPerInstance` iterations, one for each of the tokens that will be assigned to `instanceID`. At the beginning of the process, `ownership` of `instanceID` is 0. At each iteration `i`, we calculate the ownership `tokenOwnership` of the `i`$^{th}$ token as the highest multiple of `zoneCount` less or equal to $\frac{optimalInstanceOwnership - ownership}{tokensPerInstance - i}$. Then we determine the token with the highest ownership (let's say covering range `[a, b]`) of the instance with the highest ownership, and reduce their ownership by `tokenOwnership`, by placing a new token at position `a + tokenOwnership`.

Some important properties of the _spread minimizing approach_ are:
- for each `token` of the tokens calculated for instance `instanceID` and zone `zoneID`, `token % zonesCount == zoneID`.
- the approach is idempotent, i.e., if applied multiple times to the same input, it will always produce the same result.
- it guarantees consistency, i.e., by adding/removing 1 instance per zone, the number of series that are moved to another instance is at most `seriesCount/instancesCount`, where `seriesCount` and `instancesCount` are the total number of series and the total number of instances after adding/removing respectively.

**Comment by duricanikolic** [comment]
We have done some preliminary analysis of the spread, calculated as $\frac{max - min}{max}$, where $min$ and $max$ are minimal and maximal ownership of instances in the ring. We have analyzed the following rings, whose instances own `512` tokens each:
- the random token rings, i.e., rings generated by selecting `512` tokens randomly (`rt` approach)
- the real rings, i.e., rings built by using the real tokens assigned to the ingesters on some selected prod cells (`rr` approach)
- the rings built by using the _spread minimizing approach_ (`sm` approach)
The analyses are done on the following cells: `cortex-dedicated-02`, `cortex-dedicated-14` and `mimir-dedicated-17`.
The results of the analyses can be seen in the following charts, which show the comparison of the spread of the 3 rings zone-by-zone, with shuffle sharding enabled (at left) and with shuffle sharding disabled(at right).
## cortex-dedicated-02 ##
![cortex-dedicated-02](https://github.com/grafana/mimir/assets/1186801/584c34ee-79c4-4cb6-9c33-9416f0bec9f2)

## cortex-dedicated-14 ##
![cortex-dedicated-14](https://github.com/grafana/mimir/assets/1186801/1f4555b9-8361-4d16-9370-a2c7dd4e78a9)

## mimir-dedicated-17 ##
![mimir-dedicated-17](https://github.com/grafana/mimir/assets/1186801/188fe945-19c3-4893-a868-bc4b2b460fe6)

**Comment by duricanikolic** [comment]
## Shuffle sharding (cortex-prod-10) ##
In the case of shared cells with shuffle sharding active, we don't expect to have huge improvements. Nevertheless, we have analyzed the token distribution on `cortex-prod-10` and performed some experiments (by using the `rt`, `rr` and `sm` approaches introduced in the previous comment). In all experiments, the real shard sizes of the cell tenants were used.

### Spread comparison by changing the minimum shard size ###
Currently, the minimum shard size is `3`. We have performed analyses that show how the spread changes when the minimum shard size is set to `3` (current default), `6`, `9`, `12`, `15`, `120`, `126`, `240`, `480`, `486`, `492`, `498` and `504` (meaning shuffle sharding disabled).
In all the analyses the spread minimizing approach introduces some improvements. As expected, the higher the minimum shard size is the lower the spread is. Nevertheless, the minimum spread cannot be drastically changed.

![ShuffleShardByMinShardSizes](https://github.com/grafana/mimir/assets/1186801/c2adc667-4826-4d73-bd2d-0e12e6425b29)

### Spread comparison by disabling shuffle sharding of big tenants ###
We have performed an additional test: we have compared the spreads obtained by disabling shuffle sharding for all tenants of `cortex-prod-10` having `max-global-series-per-user` limit above a certain value (4M, 6M and 8M **before** replication). The results are shown in the following chart. Note: MAX represents the current default, i.e., shuffle sharding is always enabled.

<img width="1345" alt="SpreadWithShardSize0WhenTimeseriesCountLimitReachedBeforeReplication" src="https://github.com/grafana/mimir/assets/1186801/b3859015-47bb-43af-962a-c75c75f7d42b">

**Comment by duricanikolic** [comment]
## Out-of-order instance registration ##
We have analyzed how the spread in the ring built by the _spread minimizing approach_ changes when the instances are not registered with the ring in ascending, but in a random order. We have calculated the worse spreads that we could have in rings with `3`, `5`, `10`, `20`, `30`, `50`, `100`, `150` and `200` instances per zone, when we add `3`, `5` or `7` instances per zone in a random order. The permutations of new ids that give the worse spread both when we add and when we remove instances are determined (see the results at the bottom of this comment). In some cases the spread is not as good as when the instances are registered in ascending order. Nevertheless, once all `3`, `5`, or `7` instances are added or removed, the spread goes back to the values that we have always seen (below `1%`). 

For example, in the case of adding 3 instances (with ids `3`, `4`, `5`) in a zone where there are currently `3` instances (with ids `0`, `1`, `2`), permutation `[4, 3, 5]` gives the worst spread (`29.51%`). This spread is encountered when instance `4` is added, but once all `3` instances are added, the spread becomes low (`0.195%`) again. 

**Q**: What does this high spread mean for us? The instance `4` will be in the ring without instances `3` and `5` only for a limited (hopefully very short) time, so the unbalanced distribution due to a random registration of instances is not something permanent.
**A** by @pracucci: Although the unbalanced distribution is not permanent, for up to `3h` the ingester will suffer such unbalance because of all series written to the instance `4` in the short period of time before other ingesters are also registered. These series stays there in-memory until removed from the TSDB head, which will take up to `3h` (TSDB head is compacted every `2h` for samples with time between `-3h` and `-1h` ago).
**Q**: How can we fix this?
**A** by @pracucci: Maybe we can force ingesters to register in the ring only after all previous ingesters have been registered?

![WorstSpreadComparison](https://github.com/grafana/mimir/assets/1186801/f314efe7-0b75-45ce-aadd-29980ab81ab3)

**Comment by duricanikolic** [comment]
In this [PR](https://github.com/grafana/dskit/pull/321) the `SpreadMinimizingTokenGenerator`, which follows [the previously introduced approach](https://github.com/grafana/mimir/issues/4736#issuecomment-1588906897), has been added to the `dskit` repository.
We wanted to check, for each prod cell, how many tokens already present in the existing rings, would collide with the tokens generated by `SpreadMinimizingTokenGenerator` for the same configurations (number of tokens per instance, number of instances per zone and number of zones). This is something we will need to be aware of during a future migration from `RandomTokenGenerator` (which is currently in use) to `SpreadMinimizingTokenGenerator`. The following table summarizes the results. **Note**: the last column does _NOT_ show percentage (%) but **per-mille** (‰).

| cell              | #ingesters | #total tokens | #repeated tokens | ‰repeated tokens |
|----------------------|------------|---------------|------------------|------------------|
cortex-billing-01 | 6 | 0 | 3072 | 0‰
cortex-dedicated-01 | 27 | 0 | 13824 | 0‰
cortex-dedicated-02 | 225 | 2 | 115200 | 0.01736111111‰
cortex-dedicated-04 | 18 | 0 | 9216 | 0‰
cortex-dedicated-06 | 105 | 1 | 53760 | 0.01860119048‰
cortex-dedicated-08 | 30 | 0 | 15360 | 0‰
cortex-dedicated-12 | 126 | 3 | 64512 | 0.04650297619‰
cortex-dedicated-14 | 324 | 7 | 165888 | 0.04219714506‰
cortex-ops-01 | 360 | 11 | 184320 | 0.05967881944‰
cortex-prod | 45 | 0 | 23040 | 0‰
cortex-prod-01 | 261 | 4 | 133632 | 0.02993295019‰
cortex-prod-03 | 18 | 0 | 9216 | 0‰
cortex-prod-04 | 159 | 2 | 81408 | 0.02456761006‰
cortex-prod-06 | 240 | 6 | 122880 | 0.048828125‰
cortex-prod-09 | 24 | 0 | 12288 | 0‰
cortex-prod-10 | 504 | 12 | 258048 | 0.04650297619‰
mimir-dedicated-17 | 417 | 8 | 213504 | 0.03747002398‰
mimir-dedicated-20 | 162 | 3 | 82944 | 0.03616898148‰
mimir-dedicated-21 | 3 | 0 | 1536 | 0‰
mimir-dedicated-28 | 9 | 0 | 4608 | 0‰
mimir-dedicated-30 | 360 | 7 | 184320 | 0.03797743056‰
mimir-dedicated-31 | 111 | 0 | 56832 | 0‰
mimir-dedicated-33 | 33 | 1 | 16896 | 0.05918560606‰
mimir-dedicated-35 | 111 | 0 | 56832 | 0‰
mimir-dedicated-38 | 3 | 0 | 1536 | 0‰
mimir-prod-18 | 9 | 0 | 4608 | 0‰
mimir-prod-24 | 18 | 0 | 9216 | 0‰
mimir-prod-25 | 3 | 0 | 1536 | 0‰
mimir-prod-32 | 3 | 0 | 1536 | 0‰
mimir-prod-36 | 3 | 0 | 1536 | 0‰
mimir-prod-37 | 3 | 0 | 1536 | 0‰
mimir-prod-39 | 3 | 0 | 1536 | 0‰
mimir-prod-40 | 3 | 0 | 1536 | 0‰
mimir-prod-41 | 3 | 0 | 1536 | 0‰

<img width="810" alt="RepeatedTokens" src="https://github.com/grafana/mimir/assets/1186801/cb00991a-8f01-4b6a-859f-cc4ffe531aab">

**Comment by duricanikolic** [comment]
In this [PR](https://github.com/grafana/dskit/pull/321) the `SpreadMinimizingTokenGenerator`, which follows [the previously introduced approach](https://github.com/grafana/mimir/issues/4736#issuecomment-1588906897), has been added to the `dskit` repository.
We wanted to check, for some of our prod cell, how many tokens already present in the existing rings would collide with the tokens generated by `SpreadMinimizingTokenGenerator` for the same configurations (number of tokens per instance, number of instances per zone and number of zones). This is something we will need to be aware of during a future migration from `RandomTokenGenerator` (which is currently in use) to `SpreadMinimizingTokenGenerator`. The following table summarizes the results. **Note**: the last column does _NOT_ show percentage (%) but **per-mille** (‰).

| cell              | #total tokens | #repeated tokens | ‰repeated tokens |
|----------------------|---------------|------------------|------------------|
cell 1 |  0 | 3072 | 0‰
cell 2 | 0 | 13824 | 0‰
cell 3 | 2 | 115200 | 0.01736111111‰
cell 4 | 0 | 9216 | 0‰
cell 5 | 1 | 53760 | 0.01860119048‰
cell 6 | 0 | 15360 | 0‰
cell 7 | 3 | 64512 | 0.04650297619‰
cell 8 | 7 | 165888 | 0.04219714506‰
cell 9 | 11 | 184320 | 0.05967881944‰
cell 10 | 0 | 23040 | 0‰
cell 11 | 4 | 133632 | 0.02993295019‰
cell 12 | 0 | 9216 | 0‰
cell 13 | 2 | 81408 | 0.02456761006‰
cell 14 | 6 | 122880 | 0.048828125‰
cell 15 | 0 | 12288 | 0‰
cell 16 | 12 | 258048 | 0.04650297619‰
cell 17 | 8 | 213504 | 0.03747002398‰
cell 18 | 3 | 82944 | 0.03616898148‰
cell 19 | 0 | 1536 | 0‰
cell 20 | 0 | 4608 | 0‰
cell 21 | 7 | 184320 | 0.03797743056‰
cell 22 | 0 | 56832 | 0‰
cell 23 | 1 | 16896 | 0.05918560606‰
cell 24 | 0 | 56832 | 0‰
cell 25 | 0 | 1536 | 0‰
cell 26 | 0 | 4608 | 0‰
cell 27 | 0 | 9216 | 0‰
cell 28 | 0 | 1536 | 0‰
cell 29 | 0 | 1536 | 0‰
cell 30 | 0 | 1536 | 0‰
cell 31 | 0 | 1536 | 0‰
cell 32 | 0 | 1536 | 0‰
cell 33 | 0 | 1536 | 0‰
cell 34 | 0 | 1536 | 0‰

**Comment by duricanikolic** [comment]
## Preliminary Analyses (dedicated cells) of the Spread Minimizing Approach ##

We have done some preliminary analysis of the spread, calculated as $\frac{max - min}{max}$, where $min$ and $max$ are minimal and maximal ownership of instances in the ring. We have analyzed the following rings, whose instances own `512` tokens each:
- the random token rings, i.e., rings generated by selecting `512` tokens randomly (`rt` approach)
- the real rings, i.e., rings built by using the real tokens assigned to the ingesters on some selected prod cells (`rr` approach)
- the rings built by using the _spread minimizing approach_ (`sm` approach)
The analyses are done on some of our prod cells.
The results of the analyses can be seen in the following charts, which show the comparison of the spread of the 3 rings zone-by-zone, with shuffle sharding enabled (at left) and with shuffle sharding disabled(at right).
### Test 1 ###
![tested-cell-01](https://github.com/grafana/mimir/assets/1186801/f8100a9d-aef8-4d11-b78a-2cd76aad3f20)

### Test 2 ###
![tested-cell-02](https://github.com/grafana/mimir/assets/1186801/766cf548-eae4-44bd-93b5-7159b01a671f)

### Test 3 ###
![tested-cell-03](https://github.com/grafana/mimir/assets/1186801/3dce5989-5ff0-4db8-8b81-ddc95a438f35)

**Comment by duricanikolic** [comment]
## Shuffle sharding on a big prod cell ##
In the case of shared cells with shuffle sharding active, we don't expect to have huge improvements. Nevertheless, we have analyzed the token distribution on a big prod cell and performed some experiments (by using the `rt`, `rr` and `sm` approaches introduced in the previous comment). In all experiments, the real shard sizes of the cell tenants were used.

### Spread comparison by changing the minimum shard size ###
Currently, the minimum shard size is `3`. We have performed analyses that show how the spread changes when the minimum shard size is set to `3` (current default), `6`, `9`, `12`, `15`, `120`, `126`, `240`, `480`, `486`, `492`, `498` and `504` (meaning shuffle sharding disabled).
In all the analyses the spread minimizing approach introduces some improvements. As expected, the higher the minimum shard size is the lower the spread is. Nevertheless, the minimum spread cannot be drastically changed.

![ShuffleShardByMinShardSizes](https://github.com/grafana/mimir/assets/1186801/c2adc667-4826-4d73-bd2d-0e12e6425b29)

### Spread comparison by disabling shuffle sharding of big tenants ###
We have performed an additional test: we have compared the spreads obtained by disabling shuffle sharding for all tenants of the big cell having `max-global-series-per-user` limit above a certain value (4M, 6M and 8M **before** replication). The results are shown in the following chart. Note: MAX represents the current default, i.e., shuffle sharding is always enabled.

<img width="1345" alt="SpreadWithShardSize0WhenTimeseriesCountLimitReachedBeforeReplication" src="https://github.com/grafana/mimir/assets/1186801/b3859015-47bb-43af-962a-c75c75f7d42b">

**Comment by duricanikolic** [comment]
## Out-of-order instance registration ##
We have analyzed how the spread in the ring built by the _spread minimizing approach_ changes when the instances are not registered with the ring in ascending, but in a random order. We have calculated the worse spreads that we could have in rings with `3`, `5`, `10`, `20`, `30`, `50`, `100`, `150` and `200` instances per zone, when we add `3`, `5` or `7` instances per zone in a random order. The permutations of new ids that give the worse spread both when we add and when we remove instances are determined (see the results at the bottom of this comment). In some cases the spread is not as good as when the instances are registered in ascending order. Nevertheless, once all `3`, `5`, or `7` instances are added or removed, the spread goes back to the values that we have always seen (below `1%`). 

For example, in the case of adding 3 instances (with ids `3`, `4`, `5`) in a zone where there are currently `3` instances (with ids `0`, `1`, `2`), permutation `[4, 3, 5]` gives the worst spread (`29.51%`). This spread is encountered when instance `4` is added, but once all `3` instances are added, the spread becomes low (`0.195%`) again. 

**Q**: What does this high spread mean for us? The instance `4` will be in the ring without instances `3` and `5` only for a limited (hopefully very short) time, so the unbalanced distribution due to a random registration of instances is not something permanent.
**A** by @pracucci: Although the unbalanced distribution is not permanent, for up to `3h` the ingester will suffer such unbalance because of all series written to the instance `4` in the short period of time before other ingesters are also registered. These series stays there in-memory until removed from the TSDB head, which will take up to `3h` (TSDB head is compacted every `2h` for samples with time between `-3h` and `-1h` ago).
**Q**: How can we fix this?
**A** by @pracucci: Maybe we can force ingesters to register in the ring only after all previous ingesters have been registered?

![WorstSpreadComparison](https://github.com/grafana/mimir/assets/1186801/f314efe7-0b75-45ce-aadd-29980ab81ab3)

**Comment by duricanikolic** [comment]
In this [PR](https://github.com/grafana/dskit/pull/321) the `SpreadMinimizingTokenGenerator`, which follows [the previously introduced approach](https://github.com/grafana/mimir/issues/4736#issuecomment-1588906897), has been added to the `dskit` repository.
We wanted to check, for some of our prod cell, how many tokens already present in the existing rings would collide with the tokens generated by `SpreadMinimizingTokenGenerator` for the same configurations (number of tokens per instance, number of instances per zone and number of zones). This is something we will need to be aware of during a future migration from `RandomTokenGenerator` (which is currently in use) to `SpreadMinimizingTokenGenerator`. The following table summarizes the results. **Note**: the last column does _NOT_ show percentage (%) but **per-mille** (‰).

| cell              | #repeated tokens | #total tokens | ‰repeated tokens |
|----------------------|---------------|------------------|------------------|
cell 1 |  0 | 3072 | 0‰
cell 2 | 0 | 13824 | 0‰
cell 3 | 2 | 115200 | 0.01736111111‰
cell 4 | 0 | 9216 | 0‰
cell 5 | 1 | 53760 | 0.01860119048‰
cell 6 | 0 | 15360 | 0‰
cell 7 | 3 | 64512 | 0.04650297619‰
cell 8 | 7 | 165888 | 0.04219714506‰
cell 9 | 11 | 184320 | 0.05967881944‰
cell 10 | 0 | 23040 | 0‰
cell 11 | 4 | 133632 | 0.02993295019‰
cell 12 | 0 | 9216 | 0‰
cell 13 | 2 | 81408 | 0.02456761006‰
cell 14 | 6 | 122880 | 0.048828125‰
cell 15 | 0 | 12288 | 0‰
cell 16 | 12 | 258048 | 0.04650297619‰
cell 17 | 8 | 213504 | 0.03747002398‰
cell 18 | 3 | 82944 | 0.03616898148‰
cell 19 | 0 | 1536 | 0‰
cell 20 | 0 | 4608 | 0‰
cell 21 | 7 | 184320 | 0.03797743056‰
cell 22 | 0 | 56832 | 0‰
cell 23 | 1 | 16896 | 0.05918560606‰
cell 24 | 0 | 56832 | 0‰
cell 25 | 0 | 1536 | 0‰
cell 26 | 0 | 4608 | 0‰
cell 27 | 0 | 9216 | 0‰
cell 28 | 0 | 1536 | 0‰
cell 29 | 0 | 1536 | 0‰
cell 30 | 0 | 1536 | 0‰
cell 31 | 0 | 1536 | 0‰
cell 32 | 0 | 1536 | 0‰
cell 33 | 0 | 1536 | 0‰
cell 34 | 0 | 1536 | 0‰

![RepeatedTokensPerInstance](https://github.com/grafana/mimir/assets/1186801/c1f868e9-8877-4448-92c4-abc99315e47f)

**Comment by duricanikolic** [comment]
## How can we migrate to the SpreadMinimizingTokenGenerator? ##

**Comment by duricanikolic** [comment]
@pracucci do you agree we should close this issue, since `spread-minimizing` tokens fix the problem?

**Comment by pracucci** [comment]
> @pracucci do you agree we should close this issue, since `spread-minimizing` tokens fix the problem?

I do!
