### ISSUE TITLE
Enable mimir-continous-test to send otlp-http

### ISSUE THREAD

**Issue by lmickh** [grafana/mimir#5256]
#### Is your feature request related to a problem? Please describe.

The `mimir-continous-test` tool is able to validate metric paths sent over Prometheus remote write, but doesn't provide a way to validate otlp paths.  Sending metrics to or from an otel-collector or Grafana agent through otlp-http can't be test for exmaple.  Nor can you use it to test a direct oltp-http connection to the Mimir endpoint.

#### Describe the solution you'd like

Add a flag to `mimir-continous-test` that enables it to send metrics over oltp-http to an oltp-http endpoint.

**Comment by k-jingyang** [comment]
Hello, I would like to give this a stab.

Based on my understanding. This would mainly involve creating a new client based on [pkg/continuoustest/client.go](https://github.com/grafana/mimir/blob/main/pkg/continuoustest/client.go) to write via the OTLP endpoint (`POST /otlp/v1/metrics`) instead of the Prometheus endpoint. This new client will still query Mimir using the Prometheus API.

Regarding the CLI flag, I would propose a `-tests.write-protocol` flag where

```
-tests.write-protocol string (default prometheus)
    The protocol to use to write series data. Supported values are: prometheus, oltp-http
```
