### ISSUE TITLE
Slow queries dashboard shows no results (labelling issue)

### ISSUE THREAD

**Issue by nabadger** [grafana/mimir#5558]
The slow-queries dashboard uses the `name` label to lookup the `query-frontend` as per https://github.com/grafana/mimir/blob/main/operations/mimir-mixin-compiled/dashboards/mimir-slow-queries.json#L84

In our case we don't have the `name` label available to perform the lookup.

I believe this might be because the helm mimir-distributed chart does not always render it when you do not have a rolloutZone configured and when you're not making use of legacyLabels ( https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L278 )

Both `labels` and `podLabels` helpers seem to have the same logic:

- https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L198
- https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L243

Would it be best to just make the dashboard use `app_kubernetes_io_component` instead of `name` - failing that, it looks like the helm chart should support an `else` block and populate the `name` value...

If I try the same query using `app_kubernetes_io_component` I do get the right results returned

**Comment by dimitarvdimitrov** [comment]
does promtail (or Grafana Agent) automatically include pod labels as stream labels or do you have some custom configuration to convert the `app.kubernetes.io/component` label to a loki label?

**Comment by QuentinBisson** [comment]
I have the same issue, this mixin dashboard is still not working and I'm not sure how I could help because this is definitely related to how promtail logs are configured. For instance the default in the promtail chart defined here https://github.com/grafana/helm-charts/blob/fd6529c14c0f9110dfa679f1ee70529a67680091/charts/promtail/values.yaml#L515 relabel the `app.kubernetes.io/component` into `component` which makes more sense than just name here considering name could mean pod_name, component_name, release_name and so on.

Could the name label in the loki query be overridable? That way we can generate them ourselves?

Also, I'm not sure this is only a helm issue in that case :)

**Comment by QuentinBisson** [comment]
It's fine for me as we do not use meta-monitoring yet
