### ISSUE TITLE
Ingesters can get stuck in the future

### ISSUE THREAD

**Issue by bboreham** [grafana/mimir#5642]
#### Describe the bug

We had two ingesters rejecting all data for one tenant as 'too old', although it was from the current time.
Investigation showed TSDB had blocks from a week earlier.

```
ts=2023-08-01T08:54:23.27338209Z caller=grpc_logging.go:47 level=warn method=/cortex.Ingester/Push duration=135.107µs err="rpc error: code = Code(400) desc = user=redacted: the sample has been rejected because its timestamp is too old (err-mimir-sample-timestamp-too-old). The affected sample has timestamp 2023-08-01T08:54:22.335Z and is from series {redacted}" msg=gRPC
```

#### To Reproduce

Unknown.

#### Expected behavior

Data from before the retention period should be removed, and up-to-date data should be accepted.

#### Environment

This was inside Grafana Cloud.

#### Additional Context

I suspect the behaviour described here is relevant: https://github.com/prometheus/prometheus/issues/10015

Evidence:

```
/data/tsdb/redacted # ls -l
total 48
drwxr-xr-x    3 root     root          4096 Jul 22 14:59 01H5Z1RG231DZ5E9K79W0QBATT
drwxr-xr-x    3 root     root          4096 Jul 22 16:59 01H5Z8M7A3FW3R351SNZBNVE0Q
drwxr-xr-x    3 root     root          4096 Jul 22 18:59 01H5ZFFYJ3DXHQM62SBSNY5B81
drwxr-xr-x    3 root     root          4096 Jul 22 20:59 01H5ZPBNT3QYDFXK616AB827H7
drwxr-xr-x    3 root     root          4096 Jul 22 22:59 01H5ZX7D23R9N74NHQV3J6TPY2
drwxr-xr-x    3 root     root          4096 Jul 23 00:59 01H60434A34DRG8ZJ5VPCBM8D4
drwxr-xr-x    3 root     root          4096 Jul 23 01:29 01H605V28VPPCV7CPDY44T8237
drwxr-xr-x    2 root     root          4096 Jul 31 08:15 chunks_head
-rw-r--r--    1 root     root           371 Aug  1 08:21 mimir.shipper.json
-rw-r--r--    1 root     root           260 May  2 22:39 thanos.shipper.json
drwxr-xr-x    3 root     root          4096 Jul 31 08:15 wal
drwxr-xr-x    2 root     root          4096 Apr 28 11:00 wbl
/data/tsdb/redacted # ls -l wal
total 108176
-rw-r--r--    1 root     root     110765958 Jul 23 01:24 00075362
-rw-r--r--    1 root     root             0 Jul 23 01:25 00075363
-rw-r--r--    1 root     root             0 Jul 23 01:29 00075364
-rw-r--r--    1 root     root             0 Jul 31 08:14 00075365
-rw-r--r--    1 root     root             0 Jul 31 08:15 00075366
drwxr-xr-x    2 root     root          4096 Jul 31 08:15 checkpoint.00075361
/data/tsdb/redacted # ls -l chunks_head/
total 0
```

**Comment by pstibrany** [comment]
Investigation shows that affected ingesters ingested sample with very high timestamp. We don't know why exactly that happened, but we have found confirmation of such samples on all ingesters (eg. in WAL that Bryan listed above, sample had timestamp 3751659484379, or Nov 18 23:38:04 UTC 2088).

Furthermore ingesters that were restarted and loaded WAL also set "last update time" for the user's TSDB to "TSDB max time", https://github.com/grafana/mimir/blob/2fa109f1ef003e0805beeae6cb8de12ed52ac271/pkg/ingester/ingester.go#L2168-L2175

This prevented TSDBs from compaction (they were never idle) and eventual closing.

We also had cases of ingesters that ingested sample with future timestamp, but didn't restart. In those cases TSDB was eventually marked as idle, and then closed.

https://github.com/grafana/mimir/pull/5712 added check to avoid ingestion of the samples with too high timestamps.

https://github.com/grafana/mimir/pull/5786 is adding metric so that we can detect the situation earlier.

**Comment by pstibrany** [comment]
Update:

#5787 Fixed setting of TSDB of "last update" timestamp on restart.

#5822 Added `MimirIngestedDataTooFarInTheFuture` alert (warning) that triggers when Mimir ingests sample with timestamp more than 1h in the future
