### ISSUE TITLE
Docs: Fix broken link in latest Helm chart docs

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#5715]
"I'm trying to reach the following location but got a 404 instead: https://grafana.com/docs/mimir/v2.9.x/manage/monitor-grafana-mimir/collecting-metrics-and-logs/#collect-metrics-and-logs-without-the-helm-chart
The link is from here: [https://grafana.com/docs/helm-charts/mimir-distributed/latest/run-production-environment-with-helm/monitor-system-health/#monitor-the[…]-your-system](https://grafana.com/docs/helm-charts/mimir-distributed/latest/run-production-environment-with-helm/monitor-system-health/#monitor-the-health-of-your-system)"

`@JStickler` responds, "The page you're looking for (https://grafana.com/docs/mimir/v2.9.x/manage/monitor-grafana-mimir/collecting-metrics-and-logs/#collect-metrics-and-logs-without-the-helm-chart) has moved to https://grafana.com/docs/mimir/latest/operators-guide/monitor-grafana-mimir/collecting-metrics-and-logs/."

**Comment by osg-grafana** [comment]
> `@JStickler` responds, "The page you're looking for (https://grafana.com/docs/mimir/v2.9.x/manage/monitor-grafana-mimir/collecting-metrics-and-logs/#collect-metrics-and-logs-without-the-helm-chart) has moved to https://grafana.com/docs/mimir/latest/operators-guide/monitor-grafana-mimir/collecting-metrics-and-logs/."

The current `latest`, which is `v.2.9.x`:
https://grafana.com/docs/mimir/latest/operators-guide/monitor-grafana-mimir/collecting-metrics-and-logs/
https://grafana.com/docs/mimir/v2.9.x/operators-guide/monitor-grafana-mimir/collecting-metrics-and-logs/

Were moved in `next`:
https://grafana.com/docs/mimir/next/manage/monitor-grafana-mimir/collecting-metrics-and-logs/

**Comment by jdbaldry** [comment]
This is challenging because the Mimir docs referenced by the Helm chart docs in `main` is not in `main`. The Helm chart supports the latest release which is currently `v2.9.x` which is in the `release-2.9` branch.

For accurate local development, contributors and maintainers will need both the `release-2.9` and `main` branches checked out and then to supply the correct invocation of `make docs`.

In order to fix this properly, we need to revise the local development scripts for this repository and update CI to test everything correctly.
