### ISSUE TITLE
Improve the readability of y axis

### ISSUE THREAD

**Issue by zhehao-grafana** [grafana/mimir#6482]
currently, for native histogram, the y axis might not be easy to read given it is auto-generated

![image](https://github.com/grafana/mimir/assets/143556099/1ef69e13-f95f-4e2b-9c3b-56257b04a139)

**Comment by leeoniya** [comment]
this one appears to be from `admin-dev-us-central-0.grafana-dev.net`, which is running a fairly ancient version of grafana version (9.4.3). when i test that panel against a recent version, it works correctly. it was fixed by 
 https://github.com/grafana/grafana/pull/75199.

![image](https://github.com/grafana/mimir/assets/43234/70f8025e-0ef5-47aa-9980-d05e09cc061a)
