### ISSUE TITLE
Feature Request: Move `mimirclient` to `dskit`

### ISSUE THREAD

**Issue by gotjosh** [grafana/mimir#6677]
I propose we move https://github.com/grafana/mimir/tree/main/pkg/mimirtool/client to https://github.com/grafana/dskit.

Personally, I need to use the client as part of Grafana but would like to avoid importing any part of Mimir directly.  I can see this client doesn't see enough change that moving it outside of `grafana/mimir` would be a major problem. 

Any thoughts?

**Comment by 56quarters** [comment]
I'm not a fan of moving the client:

* Outside Mimir. It's very specific to Mimir and having it outside the repo would make maintenance more difficult. E.g. we moved `cortextool` to `mimirtool` inside the Mimir repo to make things easier to version together.
* I definitely don't think it belongs in dskit. It's very specific to Mimir and dskit is meant to be reusable components for the databases (and potentially other projects). 

Since the goal is calling Mimir APIs without having all of Mimir as a dependency for Grafana, maybe a little copy/paste would be acceptable? The HTTP APIs of Mimir don't change without a major version bump (I think).
