### ISSUE TITLE
Mimirtool sync flags ambiguous

### ISSUE THREAD

**Issue by andres32168** [grafana/mimir#6747]
#### Describe the bug
Hi,

the help of the mimirtool is ambiguous.
It's says it can be repeated multiple times but an issue appears with
```shell
mimirtool: error: flag 'rule-files' cannot be repeated, try --help
```

#### To Reproduce

1. Download latest mimirtool version: Mimirtool, version 2.10.4 (branch: release-2.10, revision: d1f4f1291)
2. Check the mimirtool rules sync help
```shell

./mimirtool rules sync --help
{...}
--rule-files=RULE-FILES     The rule files to check. Flag can be reused to load multiple files.
```
3. Try to sync multiple files
```shell
./mimirtool rules sync --rule-files=alerts.yaml --rule-files=rules.yaml
mimirtool: error: flag 'rule-files' cannot be repeated, try --help
```
4. See the error
1. Start Mimir (SHA or version)
2. Perform Operations(Read/Write/Others)

#### Expected behavior

Multiple rule files can be synced with 1 command

#### Environment
Mimirtool, version 2.10.4 (branch: release-2.10, revision: d1f4f1291)

#### Additional Context
---

**Comment by dimitarvdimitrov** [comment]
looking at how rule-rules is used, it should be comma-separated list on the command, line https://github.com/grafana/mimir/blob/8856cd474df3d4514ed0844061c64a06be279b18/pkg/mimirtool/commands/rules.go#L340-L347

but I also don't understand the need for that flag since all of the commands already take multiple arguments as the rule files.

I think we can just remove this flag to keep the interface simpler

**Comment by andres32168** [comment]
Well, thank you for your answer. With a comma seperated list it works very good.
Maybe it should be added to the help that a comma-seperated list is expected.
