### ISSUE TITLE
Mimir mixin Disk space utilization panels broken for mimir helm chart

### ISSUE THREAD

**Issue by jmichalek132** [grafana/mimir#7515]
#### Describe the bug
The disk space utilization panels in the mimir mixin don't work with mimir deployed using the [mimir-distributed](https://github.com/grafana/mimir/tree/main/operations/helm/charts/mimir-distributed) helm chart.

Query example [from](https://github.com/grafana/mimir/blob/main/operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json#L1066):

![image](https://github.com/grafana/mimir/assets/7171250/c34e2c8b-4f2f-4ccc-9d7b-8d0218e1c8aa)

```
max by(persistentvolumeclaim) (
  kubelet_volume_stats_used_bytes{cluster=~"$cluster", namespace=~"$namespace"} /
  kubelet_volume_stats_capacity_bytes{cluster=~"$cluster", namespace=~"$namespace"}
)
and
count by(persistentvolumeclaim) (
  kube_persistentvolumeclaim_labels{
    cluster=~"$cluster", namespace=~"$namespace",
    label_name=~"(ingester).*"
  }
)

```
Problematic part is `label_name=~"(ingester).*"` on the `kube_persistentvolumeclaim_labels` metric coming [from](https://github.com/grafana/mimir/blob/main/operations/mimir-mixin/dashboards/dashboard-utils.libsonnet#L538).

There are 2 issues with it;
* If you the kube-state-metrics service monitor from metamonitoring it will drop the `kube_persistentvolumeclaim_labels` metric due to this metric relabeling [rule](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/metamonitoring/kube-state-metrics-servmon.yaml#L21) 
* The PVCs produced don't have this label:
```
  labels:
    app.kubernetes.io/component: ingester
    app.kubernetes.io/instance: metrics
    app.kubernetes.io/name: mimir
    rollout-group: ingester
    zone: zone-a
```

#### To Reproduce

1. Start mimir distributed helm chart 
2. Deploy the mimir mixin

#### Expected behavior

For Disk space utilization panels to work.

#### Environment

- Infrastructure: Kubernetes, AKS
- Deployment tool: Helm

#### Additional Context

Not sure what would be the best way to fix this.
Things that come to mind
* Update the service monitor to not drop more used metrics by the mixin
* Allow configuring which labels is used instead of `label_name` in those panels

Willing to submit a PR to address this after feedback.

**Comment by dimitarvdimitrov** [comment]
Keeping the kube_persistentvolumeclaim_labels metric just for the pods from mimir looks tricky. Can we use the 'app.kubernetess.io/name: mimir' inside the relabelling config to pick this up? To avoid scraping other mimir clusters in the same k8s cluster we can add another 'keep' relabelling which checks the namespace label (and need to make sure it's present on all currently collected metrics)

Regarding the second problem of using different labels - is it possible to use relabelling rules so we take either 'label_rollout_group' or 'label_name' - whichever is present? I.e. replace label_name woth the other only if the other is non-empty, maybe theres something with regex we can do?

**Comment by QuentinBisson** [comment]
@dimitarvdimitrov I'm just facing this issue and would using the `app.kubernetes.io/component: ingester` label not be a better choice than rollout group?

**Comment by dimitarvdimitrov** [comment]
using `app.kubernetess.io/name: mimir` makes this slightly more reusable - we don't have to update the scraping rules every time a new component has disk (or we rename the component or add disk to an existing component, etc). If that's not possible, then `app.kubernetes.io/component` should also suffice

**Comment by QuentinBisson** [comment]
I think the issue with using `app.kubernetess.io/name` is that it would not work on specific write dashboard because it would write thé data of all Mimir components instead of just the ingester

**Comment by QuentinBisson** [comment]
See PR here https://github.com/grafana/mimir/pull/7968

**Comment by QuentinBisson** [comment]
Let me know how I can speed things up :)

**Comment by dimitarvdimitrov** [comment]
#### Using a common label on the `kube_persistentvolumeclaim_labels` selector


My suggestion in the issue was to add support for both labels in panel via `label_replace` or `label_join` promQL function. But I realized this won't work because we cannot filter on the series labels outside of the vector selector (`kube_persistentvolumeclaim_labels{...}`)


Another option for solving the selector problem is to add the standard kubernetes labels (app.kubernetes.io/*) to the jsonnet mixin and use that in the dashboards like the ones here

https://github.com/grafana/mimir/blob/f573a03208fb076f8d65375c72572528e343912f/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L226-L237

**Comment by dimitarvdimitrov** [comment]
> adding the label to the jsonnet mixin

I meant adding the label to the resources created by the jsonnet library to deploy Mimir. This will help with having a single label selector in the promQL query because it will match both jsonnet and helm deployments because they will have some label in common

> The main issue with using the `kube_persistentvolumeclaim_labels` is that the newer versions of kube-state-metrics do not expose any labels by defaults (since 2.11 I think) and they need to be explicitely asked for

That doesn't sound great. So the metric is just empty by default? I couldn't find this change in the changelog. Do you have a link to the PR or changelog entry?

**Comment by QuentinBisson** [comment]
I was wrong, this happened in kube-state-metrics 2.10 https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.10.0 (cf. the top message)

**Comment by QuentinBisson** [comment]
Regarding the fix I would assume this would be needed under `operations/mimir`? In that case I'm not sure I would be the best to fix it because I'm definitely lost in this folder

**Comment by QuentinBisson** [comment]
@dimitarvdimitrov what do you think about using something like `kubelet_volume_stats_used_bytes{cluster_id=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*(ingester)-.*\"} /\n kubelet_volume_stats_capacity_bytes{cluster_id=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*(ingester)-.*\"}\n)\n" instead of the kube-state-metrics metric?

**Comment by dimitarvdimitrov** [comment]
That's a neat idea and is much simpler too. I don't see a reason why it won't work

**Comment by QuentinBisson** [comment]
PR to fix it https://github.com/grafana/mimir/pull/8212
