### ISSUE TITLE
Docs: Standardize format of admonition blocks

### ISSUE THREAD

**Issue by seizethedave** [grafana/mimir#7667]
The Mimir docs frequently use admonition blocks that look like this:

```
{{< admonition type="note" >}}
...
{{< /admonition >}}
```

That results in a block that looks like this:
<img width="693" alt="image" src="https://github.com/grafana/mimir/assets/133913/e119e1b0-57fd-4957-86fd-cf16f67efaaf">

(note the inconsistent vertical padding in the block.)

There is a newer/better admonition style:

```
{{% admonition type="note" %}}
...
{{% /admonition %}}
```

which looks like this:

<img width="742" alt="image" src="https://github.com/grafana/mimir/assets/133913/e43a8a4b-7a4d-47ff-8149-3f246cda3267">

I think we should use the second form across the board.

**Comment by seizethedave** [comment]
Err, @jdbaldry do you know what's going on here? The writing guide [specifies](https://grafana.com/docs/writers-toolkit/write/shortcodes/#admonition) using the first syntax, though the samples there look nicer than they do in the rendered Mimir docs.

**Comment by jdbaldry** [comment]
Hey David,

The two shortcodes should produce the same admonition output. There are some differences in how Hugo evaluates the different syntaxes and Writers' Toolkit sticks with `{{<` because it's the most common and has the least complicated behavior. I can explain more if it's of interest.

My guess is that the screenshot associated with the first form in your post is actually coming from docs that use blockquote Markdown syntax. It's worth noting that the code in `main` is the "next" documentation, and the "latest" documentation is from the latest release branch.

**Comment by seizethedave** [comment]
Oh, you nailed it. I was indeed looking at "latest" which still had blockquote admonitions. Thanks!
