### ISSUE TITLE
Mismatch between ingester limiter and owned series when new ingesters are PENDING with no tokens

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#7847]
The issue is that when new ingesters come up, they [join the ring as PENDING with no tokens](https://github.com/grafana/dskit/blob/73feada6c0d7d02d419415a63fd5a31ae2a40830/ring/lifecycler.go#L638-L641), and only later generate new tokens and update their entry. There should be no delay between these two states, since the `JoinAfter` for Mimir ingesters is the default of `0`. 

However, if there happens to be a delay between ingester A joining the ring and generating new tokens, a run of the owned series service on ingester B would:
- see a lowered local limit, because there is an additional ingester in the ring
- see no change to the owned token ranges, because there have been no new tokens added to the ring.
This results in ingester B caching a new lowered local series limit, but not reducing the owned series count. Depending on how close the owned series count is to the limit, this can result in dropped samples until ingester A adds new tokens to the ring, and ingester B calculated new token ranges.

I was able to reproduce this locally by adding a new ingester with `JoinAfter` set to `60s`:
```
// Initial run of owned series service
ts=2024-03-29T05:35:10.547664799Z caller=user_tsdb.go:589 level=info component="owned series" msg="owned series: recomputed owned series for user" user=anonymous reason="new user" ownedSeriesBefore=20703 ownedSeriesNew=20703 shardSizeBefore=10 shardSizeNew=10 localLimitBefore=50000 localLimitNew=50000 duration=3.793875ms attempts=1 success=true

// New ingester added with no tokens -- local limit updated, but not owned series count
ts=2024-03-29T05:35:55.543544709Z caller=user_tsdb.go:589 level=info component="owned series" msg="owned series: recomputed owned series for user" user=anonymous reason="local series limit changed" ownedSeriesBefore=22822 ownedSeriesNew=22822 shardSizeBefore=10 shardSizeNew=10 localLimitBefore=50000 localLimitNew=25000 duration=3.914875ms attempts=1 success=true

// New ingester adds tokens -- owned series count updated
ts=2024-03-29T05:36:55.54486925Z caller=user_tsdb.go:589 level=info component="owned series" msg="owned series: recomputed owned series for user" user=anonymous reason="ring changed" ownedSeriesBefore=24829 ownedSeriesNew=12645 shardSizeBefore=10 shardSizeNew=10 localLimitBefore=25000 localLimitNew=25000 duration=6.787083ms attempts=1 success=true
```

**Comment by pr00se** [comment]
I've tested a change that only uses the count of ingesters *with tokens* in the ring to calculate the local limits

The test setup is:
- 3 zones, RF=3
- ingesters register in the ring immediately, but stay PENDING with no tokens for 60 seconds
- cluster starts with 3 ingesters, and 2 minutes later we add 3 more ingesters

before change:
![broken](https://github.com/grafana/mimir/assets/1776320/0f14cce3-f6b3-4e85-8009-94ab7f99cdfa)

after change:
![fix](https://github.com/grafana/mimir/assets/1776320/cc515fce-4105-459e-a9a4-fc4b41d6f2b0)

With the change, the addition of new ingesters with no tokens doesn't trigger an owned series recomputation because the local limit doesn't change, so we keep using the existing local limit. Once the new ingesters generate tokens and fully join the ring, the owned series is recalculated and the lowered local limit takes effect, with no sample discards in the meantime.
