### ISSUE TITLE
Chore: replace model.Metric with labels.Labels in MetricsForLabelMatchers()

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#800]
In https://github.com/grafana/mimir/pull/790 we've removed `metric.Metric` in favour of `model.Metric`. The next step could be just moving to `labels.Labels` in `MetricsForLabelMatchers()` instead of `model.Metric`. This could also save some memory allocations due to type casting.

**Comment by ch33hau** [comment]
Hi @pracucci , I am new here, can I work on this issue?

And one question regarding the code in the distributor's `MetricsForLabelMatchers()`: https://github.com/grafana/mimir/blob/main/pkg/distributor/distributor.go#L1285-L1291, this is using `model.Metric.Fingerprint()`, is that for deduplication purposes? However, I couldn't find an equivalent method in `labels.Labels` (`Hash()` is available and sounds similar, but I think `Fingerprint()` is meant for a unique identity). 

Would be great to know what the code does and find a suitable replacement. 

Thanks!

**Comment by pstibrany** [comment]
Hello.

Feel free to work on this issue.

`model.Metric.Fingerprint()` is not unique, and `labels.Labels.Hash()` is a good replacement (it uses different hashing function, but that's fine).

The code that you point to dues use `model.Metric.Fingerprint()` for deduplication purposes, but it is in fact buggy, because fingerprints are not unique:

```
func TestCollision(t *testing.T) {
	const _label1 = "ypfajYg2lsv"
	const _label2 = "KiqbryhzUpn"

	m1 := model.Metric(map[model.LabelName]model.LabelValue{model.MetricNameLabel: "logs", "_": _label1})
	m2 := model.Metric(map[model.LabelName]model.LabelValue{model.MetricNameLabel: "logs", "_": _label2})

	fmt.Println(m1.Fingerprint())
	fmt.Println(m2.Fingerprint())
}

prints:

81c55c3c0bfcf805
81c55c3c0bfcf805
```

It would be good to start with the fix to this function :)

**Comment by ch33hau** [comment]
@pstibrany thank you for the hints!
